# Generated by Django 4.2.7 on 2025-07-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletags',
            name='id',
        ),
        migrations.AlterField(
            model_name='articletags',
            name='article',
            field=models.ForeignKey(db_column='article_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.articlelists'),
        ),
    ]
